sudo: required
jdk:
  - openjdk8
services:
  - docker
branches:
  only:
    - master
env:
  - NXF_ANSI_LOG=false
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz realpath
  - sudo pip install awscli
before_script:
  - curl -fsSL get.nextflow.io | bash
script:
  - ./nextflow run . -profile docker
  - bash -x validate-ci.sh
